# Generated by Django 4.2.9 on 2024-10-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apteka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_question_number_in_tests', models.IntegerField(default=1)),
                ('right_answers_counter', models.IntegerField(default=0)),
            ],
        ),
    ]
