# Generated by Django 4.2.9 on 2024-10-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apteka', '0002_exammanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammanager',
            name='current_question_number_in_tests',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='exammanager',
            name='right_answers_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
