# Generated by Django 4.2.9 on 2024-10-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apteka', '0003_alter_exammanager_current_question_number_in_tests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammanager',
            name='current_question_number_in_tests',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
